Repository grintex/app-covid, pull requests merged in 2020-05, with the labels that each got.

#53 feat(risk-group): Adds risk group for children.
  src/pages/risk-group-description.f7.html
  src/static/images/baby-2.svg
  src/static/images/baby-boy.svg
  src/static/images/baby.svg
  src/static/images/brainstorm.svg
  src/static/images/diabetes-test-2.svg
  src/static/images/heart-problem-2.svg
  src/static/images/lose-weight.svg
Labels: enhancement

#55 Where help home
  src/js/routes.js
  src/pages/other-places-help.f7.html
  src/pages/places-help.f7.html
  src/pages/useful-phones.f7.html
  src/pages/when-help.f7.html
  src/pages/where-help.f7.html
  src/static/images/hospital.svg
  src/static/images/map.svg
  src/static/images/question-2.svg
Labels: enhancement

#56 Where help page 1
  src/pages/when-help.f7.html
  src/pages/where-help.f7.html
Labels: enhancement

#58 Where help page 2
  src/pages/places-help.f7.html
  src/pages/risk-group-quiz.f7.html
  src/static/images/hospital-2.svg
Labels: enhancement

#61 feat(where-help): Adds other places list.
  src/pages/other-places-help.f7.html
  src/static/images/bed.svg
  src/static/images/hospital-3.svg
  src/static/images/hospital-4.svg
  src/static/images/hospital-5.svg
Labels: enhancement

#63 Useful Phones
  src/app.f7.html
  src/index.html
  src/js/app.js
  src/pages/404.f7.html
  src/pages/catalog.f7.html
  src/pages/dynamic-route.f7.html
  src/pages/form.f7.html
  src/pages/home.f7.html
  src/pages/mask.f7.html
  src/pages/news.f7.html
  src/pages/product.f7.html
  src/pages/request-and-load.f7.html
  src/pages/settings.f7.html
  src/pages/stats.f7.html
  src/pages/symptoms.f7.html
  src/pages/useful-phones.f7.html
Labels: enhancement

#69 fix(where-help): Fixes error in images' path.
  src/pages/when-help.f7.html
  src/pages/where-help.f7.html
Labels: bug

#70 Config assets
  assets-src/cordova-android-icon.png
  assets-src/cordova-splash-screen.png
  cordova/res/icon/android/mipmap-hdpi/ic_launcher.png
  cordova/res/icon/android/mipmap-ldpi/ic_launcher.png
  cordova/res/icon/android/mipmap-mdpi/ic_launcher.png
  cordova/res/icon/android/mipmap-xhdpi/ic_launcher.png
  cordova/res/icon/android/mipmap-xxhdpi/ic_launcher.png
  cordova/res/icon/android/mipmap-xxxhdpi/ic_launcher.png
  cordova/res/icon/android/playstore-icon.png
  cordova/res/screen/android/drawable-hdpi/screen.png
  cordova/res/screen/android/drawable-ldpi/screen.png
  cordova/res/screen/android/drawable-mdpi/screen.png
  cordova/res/screen/android/drawable-xhdpi/screen.png
  cordova/res/screen/android/drawable-xxhdpi/screen.png
  cordova/res/screen/android/drawable-xxxhdpi/screen.png
  framework7.json
Labels: enhancement

#113 Bug fixes
  src/pages/infected.f7.html
  src/pages/places-help.f7.html
  src/static/images/loupe.svg
Labels: bug

#123 Bug fixes
  src/pages/other-places-help.f7.html
  src/pages/useful-phones.f7.html
  src/pages/where-help.f7.html
  src/static/images/cough-2.svg
  src/static/images/listening.svg
Labels: bug, enhancement

#126 Bug fix
  src/pages/infected-quiz.f7.html
  src/pages/risk-group-quiz.f7.html
  src/pages/useful-phones.f7.html
  src/static/images/calling.svg
Labels: enhancement

#130 Bug fix
  src/pages/diagnosis.f7.html
  src/pages/risk-group-quiz.f7.html
Labels: bug, enhancement

#144 feat(where-help): changes page main text
  src/pages/where-help.f7.html
Labels: enhancement

#145 feat(about-covid): changes contamined icon
  src/pages/about-covid.f7.html
  src/static/images/contamined.svg
Labels: enhancement
